### PR TITLE
Use beyla 1.3.3 with k8s discovery

### PR DESCRIPTION
**Pull request by aabmass**
Similar to #86, but for the servicegraph recipe.

- Upgrade beyla
- Move to YAML based config, selecting only pods
- Add rbac config for Beyla to watch pods
- ~Move k8s attributes detection into beyla, including updating RBAC~

Tested the graphgen script is still working and the CPU/Memory usage of beyla/otel-collector are the same or better:
image

### CODE REVIEW

**Review by dashpole — APPROVED** [review]

**Comment by aabmass** [comment]
@dashpole I left in the k8sattributes processor since I will use it to lookup both server and client pod names in the next PR, which Beyla doesn't do right now.

**Comment by dashpole** [comment]
do we still need the rbac changes and the k8s detection config?

```yaml
    attributes:
      kubernetes:
        enable: true
```

**Comment by aabmass** [comment]
@dashpole see https://github.com/grafana/beyla/issues/673

I could go back to `BEYLA_SYSTEM_WIDE` since we didn't see cardinality issues with the spanmetrics receiver as an alternative.

**Review by dashpole — APPROVED** [review]
No, this is OK.  IIRC, the memory usage is still lower this way.

**Pull request merged**
